# Generated by Django 5.2.8 on 2025-11-26 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('lugar', models.CharField(blank=True, max_length=200)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoROI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Identificador interno del ROI (por ejemplo ROI-2025-001).', max_length=50, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('cliente', models.CharField(blank=True, max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_recepcion', models.DateTimeField(auto_now_add=True)),
                ('fecha_evento', models.DateField(blank=True, null=True)),
                ('fecha_limite_oferta', models.DateField(blank=True, null=True)),
                ('estado_urgencia', models.CharField(choices=[('URGENTE', 'Urgente'), ('NO_URGENTE', 'No urgente'), ('EVENTO_CERCANO', 'Evento cercano'), ('EVENTO_LEJANO', 'Evento lejano')], default='NO_URGENTE', max_length=20)),
                ('estado_proceso', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_ANALISIS', 'En análisis'), ('OFERTA_GENERADA', 'Oferta generada'), ('CERRADO', 'Cerrado')], default='PENDIENTE', max_length=20)),
                ('origen_clasificacion', models.CharField(choices=[('MANUAL', 'Manual'), ('N8N', 'n8n'), ('AUTOMATICO', 'Automático')], default='MANUAL', max_length=20)),
                ('motivo_urgencia', models.TextField(blank=True, help_text='Explicación de por qué se clasificó con este nivel de urgencia (puede venir de n8n/IA).')),
                ('enlace_documento', models.URLField(blank=True, help_text='URL al ROI (Drive, KVC, etc.).')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_roi_creados', to=settings.AUTH_USER_MODEL)),
                ('evento_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos_roi', to='events.evento')),
            ],
            options={
                'ordering': ['-fecha_recepcion'],
            },
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('completada', models.BooleanField(default=False)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas', to='events.evento')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas', to='people.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='SubTarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('descripcion', models.TextField(blank=True)),
                ('completada', models.BooleanField(default=False)),
                ('tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subtareas', to='events.tarea')),
            ],
        ),
    ]
