# Generated by Django 5.2.8 on 2025-11-26 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentoroi',
            options={'ordering': ['fecha_evento', '-fecha_recepcion']},
        ),
        migrations.AddField(
            model_name='documentoroi',
            name='archivo',
            field=models.FileField(blank=True, help_text='Archivo del ROI (PDF, DOCX, etc.).', null=True, upload_to='roi/'),
        ),
    ]
