# Generated by Django 5.2.8 on 2025-11-26 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_documentoroi_options_documentoroi_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentoroi',
            name='motivo_urgencia',
            field=models.TextField(blank=True, help_text='Explicación de por qué se clasificó con este nivel de urgencia.'),
        ),
        migrations.AlterField(
            model_name='documentoroi',
            name='origen_clasificacion',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATICO', 'Automático'), ('N8N', 'Integración externa')], default='MANUAL', max_length=20),
        ),
    ]
